# Generated by Django 3.2.9 on 2021-12-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=225, verbose_name='State')),
                ('S_C', models.CharField(max_length=225, verbose_name='State Code')),
                ('Year', models.CharField(max_length=225, verbose_name='Year')),
                ('Month', models.CharField(max_length=225, verbose_name='Month')),
                ('Max', models.FloatField(verbose_name='Avg Daily Max Air Temperature (F)')),
                ('Min', models.FloatField(verbose_name='Avg Daily Min Air Temperature (F)')),
            ],
        ),
    ]
