# Generated by Django 3.2.9 on 2021-12-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GW', '0003_auto_20211210_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
