# Generated by Django 3.2.9 on 2021-12-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GW', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=225, verbose_name='State')),
                ('S_C', models.CharField(max_length=225, verbose_name='State Code')),
                ('Year', models.CharField(max_length=225, verbose_name='Year')),
                ('Max', models.FloatField(verbose_name='Avg Daily Max Air Temperature (F)')),
                ('Min', models.FloatField(verbose_name='Avg Daily Min Air Temperature (F)')),
            ],
        ),
    ]
